name: "units-test"
on:
  pull_request:
  push:

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        resultPath: examples/example_with_group.json
        token: ${{ secrets.GITHUB_TOKEN }}
