name: "unit-tests"
on:
  pull_request:
    branches: ["main"]

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        comment-subject: Coverage Report!
        result-path: examples/example_with_group.json
        token: ${{ secrets.GITHUB_TOKEN }}
